# Generated by Django 4.1.3 on 2022-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=30)),
                ("lastName", models.CharField(max_length=30)),
                ("accountNumber", models.IntegerField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
            ],
        ),
    ]
